version: '3'
services:

  redis:
    image: redis
    command: /home/redis.conf 
    volumes:
      - ./redis/conf:/home
      - ./redis/data:/data
    container_name: redis-service
    ports:
    - "6379:6379"
    networks:
      - cockpit-net 

  payara:
    image: payara/server-full
    volumes:
      - ./../target/autodeploy:/opt/payara/deployments
    container_name: payara-service
    ports:
    - "4848:4848"
    - "8080:8080"
    links: 
    - redis
    networks: 
      - cockpit-net


  
networks:
  cockpit-net:
